name:                poc
version:             0.1.0.2
github:              "suhrawardi/poc"
license:             BSD3
author:              "Jarra"
maintainer:          "suhrawardi@gmail.com"
copyright:           "2018 Jarra"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/suhrawardi/poc#readme>

dependencies:
- base >= 4.7 && < 5
- Euterpea > 2.0.0 && < 2.1.0
- alsa-seq

library:
  source-dirs: src

executables:
  poc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - poc

tests:
  poc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - poc
